### ISSUE TITLE
Secret propertysource when using yaml

### ISSUE THREAD

**Issue by gluehbirnenkopf** [fabric8io/spring-cloud-kubernetes#101]
Hi,

I want to use a secret inside my spring boot application as property.
Im already using configmaps successfully, but secrets just dont work for me.

Secret:

```apiVersion: v1
kind: Secret
metadata:
   name: testservice
type: Opaque
data:
   camunda.bpm.admin-user.password: somebase64string==`
```
env variables in the container:
```        env:
        - name: spring.cloud.kubernetes.config.enabled
          value: "true"
        - name: spring.cloud.kubernetes.config.enableApi
          value: "true"         
        - name: spring.cloud.kubernetes.secrets.enabled
          value: "true"
        - name: spring.cloud.kubernetes.secrets.enableApi
          value: "true"   
        - name: spring.cloud.kubernetes.config.name
          value: testservice
        - name: spring.cloud.kubernetes.config.paths
          value: /home/configmaps
        - name: spring.cloud.kubernetes.secrets.name
          value: testservice
```
Spring container startup:
```
2019-02-28 07:25:55.278  INFO 1 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: SecretsPropertySource {name='secrets.testservice.dev-192'}
```

And finally, my application.yaml
```
camunda:
    bpm:
        admin-user:
            id: testservice
            password: somepasswordwhichgetsoverwrittenhopefully!!!!
            firstName: dev
            lastName: dev
```

Question:
Can I use the secret "camunda.bpm.admin-user.password", which is application.property like notation although im using application.yaml?

https://github.com/fabric8-quickstarts/spring-boot-camel-config also uses application.properties.
Anybody has an suggestion, or does spring cloud kubernetes not support application.yaml for secret configuration?
