### ISSUE TITLE
KubernetesAutoConfiguration ignores properties

### ISSUE THREAD

**Issue by asarkar** [fabric8io/spring-cloud-kubernetes#78]
`KubernetesAutoConfiguration` depends on the injected `KubernetesClientProperties` but it seems that none of the properties are picked up and defaults are used. Thus the `KubernetesClient` is always created with default properties.
The workaround I'm doing right now is as follows but this is flies in the face of auto configuration.

```
@SpringBootApplication
@EnableConfigServer
@RestController
public class ConfigServerApp {

    public static void main(String[] args) {
        SpringApplication.run(ConfigServerApp.class, args);
    }

    @Autowired
    KubernetesClientProperties k8sClientProperties;

    @Autowired
    Config k8sClientConfig;

    @RequestMapping(path = "/pods", produces = APPLICATION_JSON_UTF8_VALUE)
    public Collection<Pod> pods() {
        Config config = new Config();
        config.configFromSysPropsOrEnvVars(k8sClientConfig);
        config.setMasterUrl(k8sClientProperties.getMasterUrl());
        config.setNamespace(k8sClientProperties.getNamespace());

        KubernetesClient k8sClient = new DefaultKubernetesClient(config);

        return k8sClient.pods().list().getItems();
    }
}
```

In the `application.yml`:

```
server.port: 8888
spring.application.name: config
spring.cloud.config.server.git.uri: git@...

spring.cloud.kubernetes:
  client:
    masterUrl: http://x.x.x.x:8080
    namespace: whatever
```
